plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.1'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'jacoco'
    id 'org.asciidoctor.jvm.convert' version '3.3.2'
}

group = 'com.ecommerce'
version = '1.0'
java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.projectlombok:lombok:1.18.22'

    // JWT 의존성 추가
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    implementation 'io.jsonwebtoken:jjwt-impl:0.12.3'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.12.3'

    // Elasticsearch 의존성 추가
    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
    implementation 'org.springframework.kafka:spring-kafka'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    // Spring REST Docs 의존성 추가
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

ext {
    set('snippetsDir', file("build/generated-snippets"))
    set('docsOutputDir', file("build/docs/asciidoc"))    // API 문서가 생성되는 경로
    set('projectDocsDir', file("src/main/resources/static/docs"))    // 생성된 API 문서를 복사할 경로
}

tasks.named('bootJar') {
    dependsOn 'asciidoctor'    // asciidoctor 수행 후 bootJar 수행
}

test {
    doFirst { delete(snippetsDir) }    // test 수행 전 실행
    jacoco {
        destinationFile = file("$buildDir/jacoco/jacoco.exec")
    }
    outputs.dir snippetsDir
    useJUnitPlatform()

    finalizedBy 'jacocoTestReport'
}

tasks.named('asciidoctor') {
    doFirst {    // asciidoctor 수행 전 실행
        delete(docsOutputDir)    // 기존 생성된 API 문서 삭제
        delete(projectDocsDir)    // 기존에 복사된 API 문서 삭제
    }
    inputs.dir snippetsDir
    dependsOn test
    doLast {    // asciidoctor 수행 완료 후 실행
        copy {    // 생성된 API 문서를 지정된 경로에 복사
            from docsOutputDir
            into projectDocsDir
        }
    }
}

jacoco {
    toolVersion = '0.8.12'
}

jacocoTestReport {
    reports {
        html.required.set(true)
        xml.required.set(true)
        csv.required.set(true)

        xml.destination file("${buildDir}/jacoco/index.xml")
        html.destination file("${buildDir}/jacoco/index.html")
        csv.destination file("${buildDir}/jacoco/index.csv")
    }

    afterEvaluate {
        classDirectories.setFrom(
                files(classDirectories.files.collect {
                    fileTree(dir: it, excludes: [
                            '**/*Application*',
                            '**/exception/**',
                            '**/dto/**',
                            '**/entity/**',
                            '**/repository/**',
                            '**/document/**',
                            '**/common/**',
                            '**/config/**',
                            '**/utils/**',
                            '**/trigger/**',


                            // 현재 사용하지 않는 코드(학습용으로 남겨둔 코드)
                            '**/JwtLogoutFilter*',
                            '**/handler/**',
                            '**/SigninController*',
                            '**/SessionSigninService*'
                    ])
                })
        )
    }

    jacocoTestCoverageVerification {
        violationRules {
            rule {
                enabled = true

                element = 'CLASS'

                limit {
                    counter = 'LINE'
                    value = 'COVEREDRATIO'
                    minimum = 0.80
                }

                excludes = [
                        '*.*Application',
                        '*.exception.*',
                        '*.dto.*',
                        '*.entity.*',
                        '*.repository.*',
                        '*.document.*',
                        '*.common.*',
                        '*.config.*',
                        '*.utils.*',
                        '*.trigger.*',

                        // 현재 사용하지 않는 코드(학습용으로 남겨둔 코드)
                        '*.JwtLogoutFilter',
                        '*.handler.*',
                        '*.SigninController',
                        '*.SessionSigninService'
                ]
            }
        }
    }

    // test -> jacocoTestReport -> jacocoTestCoverageVerification 실행
    finalizedBy 'jacocoTestCoverageVerification'
}