spring:
  profiles:
    active: dev
    include: db
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        batch_size=50
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: INFO
    com.wanted.sns_feed_service: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE